### ISSUE TITLE
Not sync

### ISSUE THREAD

**Issue by grand96** [ForgeNet/ForgeCoin#1]
Wallet not sync, 0 connection
Sorry, No, sync good

**Comment by BeardFlux** [comment]
Thanks for letting me know!  All wallets should be syncing fine.  If you're experiencing sync errors and it's been longer than 24 hours, I recommend deleting the Forge executable, re-downloading, and relaunching.  Always, Always, Always ensure you have backed up your wallet.dat file in %APPDATA% > Roaming > Forge or that you have your Forge address and Private Keys backed up.
